#통합 yml 파일
spring:
  profiles:
    active: local
    include:
    - key-profile
  # mustache:
  #   prefix: classpath:/static/
  #   suffix: .html
  # mvc:
  #   static-path-pattern: /static/**
  # resources:
  #   static-locations: classpath:/static/
  #   add-mappings: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database: oracle
  messages:
    basename: classpath:/messages/exception
    encoding: UTF-8
  social:
    kakao:
      client_id: e1a42c36f99cb8171837a0b93eff564d
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:8080
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    
#Log    
logging:
  level:
    org.hibernate: info
    
#Jasype config
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
