#통합 yml 파일
spring:
  profiles:
    active: dev 
  jpa:
    hibernate:
      ddl-auto: none #데이터 베이스 초기화 전략 사용 안함
    show-sql: true 
    database: oracle
#Log    
logging:
  level:
    org.hibernate: info
    
#Jasype config
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
   
---
#개발용 설정
spring:
  profiles: dev
  datasource: 
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(gwaxu2RhZw2ewtDV1m9fkbij1ScFK+dyAq+5eCkTEO5EBvXBaOGNDMn7QvKwRKpp)
    username: ENC(3sZQfEjo8VlXTEZNkLYfI2t4LLG5y++l)
    password: ENC(/2qXEhOsc0gbx+rFi9Q5bc2YHFaSYWBZ)

---
#운영용 설정
spring:
  profiles: env
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(0tacGmbv1kcjrIOJOOCcD0Whmk3dWb+O7+JehQFyJ7tJfZUpPGYmkBqrBzHvEcvYO6w6fIkqDNoqOCO9EbvZEp3ln9yB/LzX)
    username: ENC(YeiNNcnAmSW7bZ0rhIpyp9pt01pn3dlK)
    password: ENC(sZTsM2RYrt6SQz14lYJTDA+TeoJLbeN5c5SEGDxtveU=)