# kimsboard 프로젝트의 빠른 개발과 생산성 향상을 위해 CI/CD tool인 Github Actions를 사용
# 첫 번째 버전은 백엔드(Java) 기반의 프로젝트의 의존성 관리, 패키징, 테스팅, 컴파일 등을 관리하는 gradle용 workflow
# 두 번째 버전은 프론트엔드(React.js) 기반의 프로젝트의 모듈관리 npm의 workflow를 추가할 예정
name: kimsboard_build_deploy_workflow_v1

# 환경 변수 $변수명 으로 사용
# ex) $PROJECT_NAME
env: 
  PROJECT_NAME : kimsboard
  BUCKET_NAME : webservice-deploy-storage

# master 브런치로 push할 때만 동작
on:
  push:
    branches: [ master ]

jobs:
  # build용 job
  build:
    # runner의 환경
    runs-on: ubuntu-latest
    
    # 실행할 작업들
    steps:

    # 워크플로가 쓰인 프로젝트의 github 저장소의 $GITHUB_WORKSPACE에 접근할 수 있게 해줌
    # https://github.com/actions/checkout 
    - name: Checkout github workspace
      uses: actions/checkout@v2
      
    # Java파일 사용을 위한 Java 환경을 다운로드
    # https://github.com/actions/setup-java
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk 
        architecture: x64

    # gradlew 실행권한 주기
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    # 속도 향상을 위해 캐시 사용 
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    # gradle build
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
      
    # zip으로 압축
    # 현재 directory를 현재 경로에 build.zip 이름으로 압축
    # -r 하위경로까지 모두다라는 옵션 
    - name: Compress the result into zip file
      run: zip -r ./build.zip .
      shell: bash
    
    # aws 인증서비스
    # github repository에서 Setting에서 사용할 암호화된 변수
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
    
    # Upload to S3 stroage
    - name: Upload to S3
      run: aws s3 cp build.zip s3://$BUCKET_NAME/deploy/$PROJECT_NAME.zip --region ap-northeast-2        
    
    # AWS CodeDeploy 실행 
    - name: Code Deploy
      run: aws deploy create-deployment --application-name WebserviceCodeDeploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name kimsboard --s3-location bucket=$BUCKET_NAME, bundleType=zip, key=deploy/$PROJECT_NAME.zip
